FEAT: Created About Us Page
workshopapps/twitterdevanswers.web pull request #82
Opened 2022-12-02 20:12 UTC by nnaemekaxi

FEAT: Created About Us Page

2022-12-03 17:52 UTC, mrcoded requested changes
include changes as requested to include the two pages you effected changes in with detailed explanation

2022-12-03 17:55 UTC, mrcoded commented
and why do we have commented code in app.jsx? did u rename the existing page or created a different file? it is important you pay attention to instructions
// import About from './pages/About/index';
import AboutUs from './pages/AboutUs/AboutUs'

2022-12-03 19:45 UTC, nnaemekaxi commented
> and why do we have commented code in app.jsx? did u rename the existing page or created a different file? it is important you pay attention to instructions // import About from './pages/About/index'; import AboutUs from './pages/AboutUs/AboutUs'

There was an about us page from the old designs. so i commented it out and changed the route to the new design

2022-12-04 14:19 UTC, mrcoded approved these changes

2022-12-04 15:20 UTC, merged