FE-81: Functionalities and design update for edit profilepage
workshopapps/twitterdevanswers.web pull request #83
Opened 2022-12-03 15:13 UTC by Bobbyjsx

2022-12-03 15:45 UTC, mrcoded requested changes
confirm that all texts for stack and experience levels are completed and updated, more research on numerous available stacks will be good. the installation of the snake case dependency wasn't communicated in advance, look for a way without dependecy or give more clarity why this is necessary

2022-12-03 15:46 UTC, mrcoded commented
also no description, images as to what was done.

2022-12-04 07:02 UTC, Bobbyjsx commented
i have effected changes to my code. and  updated my  API  link to the orignial hng link  https://api.devask.hng.tech

2022-12-04 15:48 UTC, mrcoded approved these changes

2022-12-04 15:49 UTC, merged